Document: cmus
Title: Debian cmus Manual
Author: <insert document author here>
Abstract: This manual describes what cmus is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cmus/cmus.sgml.gz

Format: postscript
Files: /usr/share/doc/cmus/cmus.ps.gz

Format: text
Files: /usr/share/doc/cmus/cmus.text.gz

Format: HTML
Index: /usr/share/doc/cmus/html/index.html
Files: /usr/share/doc/cmus/html/*.html
